### ISSUE TITLE
Possible to install as a plugin?

### ISSUE THREAD

**Issue by ericelliott** [johnstonbl01/eslint-no-inferred-method-name#3]
Is it possible to install this rule as an eslint plugin so you don't have to copy the file into the rules directory? That would significantly enhance the install experience.

**Comment by ericelliott** [comment]
Example of an ESLint plugin: https://github.com/yannickcr/eslint-plugin-react

**Comment by johnstonbl01** [comment]
I agree. Should be possible. I'll look into it!

**Comment by ericelliott** [comment]
:+1:

**Comment by ericelliott** [comment]
Any luck on this?

**Comment by johnstonbl01** [comment]
Finishing up another project in the next few days. It's the next thing on my list!

**Comment by ericelliott** [comment]
Great. =)

**Comment by johnstonbl01** [comment]
@ericelliott Done. :+1: 

Let me know if you run into any issues. If everything works out, let me know and I'll close this issue.

**Comment by johnstonbl01** [comment]
Closing - plugin change and NPM install package appears to be working as expected.

**Comment by ericelliott** [comment]
Nice. =)
