### ISSUE TITLE
Can't get it to work with the example in the readme.

### ISSUE THREAD

**Issue by ferhtgoldaraz** [johnstonbl01/eslint-no-inferred-method-name#5]
I'm trying to get this plugin working, but I can't. I've created a repo with only the readme's example and configuration, but still no luck.

Minimal reproduction case:

https://github.com/ferhtgoldaraz/issue-eslint-no-inferred-method-name

If I do:
```bash
❯ $(npm bin)/eslint index.js
```

I get no warnings, no errors, no nothing.

**Comment by johnstonbl01** [comment]
Resolved by #6. Apologies for the project being stale for so long!
